# Site settings
title: Open Source Web Apps
description: > # this means to ignore newlines until "baseurl:"
  Directory of Open Source Web Apps
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://opensourcewebapps.github.io" # the base hostname & protocol for your site

collections:
  apps:
    output: true
  category:
    output: true
  language:
    output: true
  database:
    output: true
  license:
    output: true

defaults:
  -
    scope:
      type: "apps"
    values:
      layout: "app"
  -
    scope:
      type: "category"
    values:
      layout: "category"
  -
    scope:
      type: "language"
    values:
      layout: "language"
  -
    scope:
      type: "database"
    values:
      layout: "database"
  -
    scope:
      type: "license"
    values:
      layout: "license"

# Build settings
markdown: kramdown
